# Potential: "intrinsic energy of inertia"


## Interdependencies of Fields: Electro-Magnetic System (Maxwell conditions)

{{< include C:/Users/erine/Desktop/Physics-Explorations/Content_repository/EMF.qmd >}}



## Potential by charge density $\varrho$ and current density $j \hat{=} \frac{\varrho}{t}$

Wave equation that determines Potential:
$$\begin{split} &
\Delta \cdot U - \frac{1}{c^2} \frac{\partial^2}{\partial t^2} U = J
\end{split}$${#eq-potignit}

Potential caused by "ignition J" (inhomgenity) from source at rest, v = 0:
$$\begin{split} &
U = -\frac{1}{2\pi} \int \frac{J}{\left | r  \right |} \, dr'
\end{split}$${#eq-potelec}

Mulitipol approximation approaching Potential $U = \sum_{i=1}^\infty U_i \;,\; i \in \mathbb{N}$:

1. **Monopol** with charge $Q$ scalar dominance (point charge = one pole):
$$\begin{split} &
    U_1 = \frac{1}{2} \frac{1}{2\pi} \frac{1}{\varepsilon_0} \frac{1}{r} Q = 
    \frac{1}{4\pi\varepsilon_0} \frac{1}{r} \int \varrho \, d^3r'
\end{split}$${#eq-monopolpot}

2. **Dipol** Potential with dipol momentunm $p$ vector dominance ("one electromagnetic neadle with one pole on each side = two poles"), $Q = (+q) + (-q) = 0$:
$$\begin{split} &
    U_2 = \frac{1}{2} \frac{1}{2\pi} \frac{1}{\varepsilon_0} \frac{1}{r^2} \cdot \left( p \cdot e_r \right) =
    \frac{1}{4\pi\varepsilon_0} \frac{1}{r^3} \left( p \cdot r \right) = 
    -\frac{1}{4\pi\varepsilon_0} \cdot \left( p \cdot \nabla\frac{1}{r} \right) =
    \newline & 
    \frac{1}{4\pi\varepsilon_0} \frac{1}{r^3} p \cos\varphi = 
    \frac{1}{4\pi\varepsilon_0} \left( \frac{q}{\left| r - \frac{d}{2}e_z \right|} - \frac{q}{\left| r + \frac{d}{2}e_z \right|} \right) = 
    \frac{1}{4\pi\varepsilon_0} \frac{1}{r^2} \int r' \varrho \, d^3r'
\end{split}$${#eq-dipolpot}

3. **Quadrupol** Potential with quadrupol mementum $Q_{ij}$ tensor dominance ("two neadles with two poles each = four poles"):
$$\begin{split} &
    U_3 = \frac{1}{2^2} \frac{1}{2\pi} \frac{1}{\varepsilon_0} \frac{1}{r^3} \cdot \left(  e_r^T \cdot Q_{ij} \cdot e_r \right) = 
    \frac{1}{4\pi\varepsilon_0} \frac{1}{r^5} Q_{ij} x_i x_j = 
    \frac{1}{8\pi\varepsilon_0} \frac{1}{r^3} \int \varrho \left[ 3 \left( e_r\cdot r' \right)^2  - r'^2 \right] \, d^3r'
\end{split}$${#eq-quadrupolpot}




## elec. Potential structure
$J = -\frac{1}{\varepsilon_0} \varrho$
$$\begin{split} &
U_e \coloneqq \Phi 
\newline & 
\stackrel{\textnormal{elec. charge dens.=}\varrho}{=}
\frac{1}{4\pi} \frac{1}{\varepsilon_0} \int \frac{\varrho}{\left | r  \right |} \, dr'
\newline & 
\> \hat{=} \>
\frac{1}{2} \frac{1}{2\pi} \frac{1}{\left | r \right |} \frac{1}{\varepsilon_0} Q = 
\frac{1}{2} \frac{1}{2\pi} \frac{1}{\left | r \right |} \frac{1}{\varepsilon_0} It
\end{split}$${#eq-potelec}

## magn. Potential structure
$J = -\mu_0 j$
$$\begin{split} &
U_m \coloneqq \boldsymbol{A} 
\newline &
\stackrel{\textnormal{elec. current dens.=}j}{=}
\frac{\mu_0}{4\pi} \int \frac{j}{\left | r  \right |} \, dr'
\newline &
\> \hat{=} \>
\frac{1}{2} \frac{1}{2\pi} \frac{1}{\left | r \right |} \mu_0 I =
\frac{1}{2} \frac{1}{2\pi} \frac{1}{\left | r \right |} \frac{1}{c^2 \varepsilon_0} I =
\frac{1}{c^2} \frac{1}{t} U_e 
\newline &
\stackrel{\textnormal{source in uniformal movement,} v = const. \neq 0}{=}
\frac{1}{2} \frac{1}{2\pi} \frac{1}{\left( \left | r \right | - r\cdot\frac{v}{c} \right)} \mu_0 Qv
\newline &
=
\frac{1}{2} \frac{1}{2\pi} \frac{1}{\left( \left | r \right | - r\cdot\frac{v}{c} \right)} \frac{1}{c^2 \varepsilon_0} vQ
\newline & 
=
\frac{1}{2} \frac{1}{2\pi} \frac{1}{\left( \left | r \right | - r\cdot\frac{v}{c} \right)} \frac{1}{c^2 \varepsilon_0} Itv = 
\frac{1}{2} \frac{1}{2\pi} \frac{1}{\left( \left | r \right | - r\cdot\frac{v}{c} \right)} \frac{1}{c^2 \varepsilon_0} Ir
\end{split}$${#eq-potmagn}

\

## Electric endogen energy 

- Bond Energy
- Binding Energy

$E_{pot} = mc^2$

$$\begin{split} &
e = \textnormal{electron charge} \qquad
q = ne = \textnormal{charge} \qquad
n \in \mathbb{N}
\end{split}$${#eq-echarge}

$$\begin{split} &
\textnormal{Potential} \qquad
U = 
\frac{E_{pot}}{q} = 
\frac{\left( mc^2 \right)^2}{ne} = 
\frac{m}{q} m c^4 = 
\kappa m c^4
\end{split}$${#eq-potential-1}


## Electric induced energy (exogenous excitation)

- Ionisation Energy
- Exitation Energy

$E_{kin} = \frac{1}{2}mv^2 \> \hat{=} \> \left( pc \right)^2 \> \hat{=} \> h\nu = \hbar\omega$

$E_{kin}$ Energy density electric:
$$\begin{split} &
w_e = \frac{1}{2} \varepsilon_0 \mathscr{E}^2
\end{split}$${#eq-energydensity-e}

$E_{kin}$ Energy density magnetic:
$$\begin{split} &
w_m = \frac{1}{2} \frac{1}{\mu_0} \mathscr{B}^2
\end{split}$${#eq-energydensity-m}

$E_{kin}$ Electric Energy:
$$\begin{split} &
W_e = \frac{1}{2} CU^2
\end{split}$${#eq-electricenergy}

$E_{kin}$ Magnetic Energy:
$$\begin{split} &
W_m = \frac{1}{2} LI^2
\end{split}$${#eq-magneticenergy}

### Power:
$$\begin{split} &
P = VI = (U_1 - U_2) \frac{Q}{t} = 
\frac{E_1 - E_2}{t} = \frac{W}{t} = \frac{Fr}{t} = Fv 
\end{split}$${#eq-power}

### Frequency:
$$\begin{split} &
\omega = \dot{\rho} = \frac{v}{r} = 2 \pi \nu = k \lambda \frac{1}{T} =
\sqrt{\frac{k}{m}}
\newline &
\stackrel{vacuum}{=}
kc
\stackrel{matter}{=}
k \frac{c}{\eta} = kc \frac{\tan\beta}{\tan\alpha}
\newline &
\stackrel{\text{electromagnetic}}{=}
k c \left( \mathscr{E_\beta}^{-1} \mathscr{E_\alpha} \right)^{-1} = 
k c \frac{\varepsilon_\beta}{\varepsilon_\alpha} = 
k c \sqrt{\frac{\varepsilon_0\mu_0}{\varepsilon\mu}}
\newline &
\> \hat{=} \>
\frac{1}{\sqrt{LC}} \sqrt{1 - \frac{C}{L}R^2}
\approx
\frac{1}{\sqrt{LC}}
\newline &
\stackrel{thermal}{=}
...
\newline &
\stackrel{gravitation}{=}
\sqrt{\frac{g}{r}}
\end{split}$${#eq-freq}

### Phase:
$$\begin{split} &
\varphi = k \left( \vec{r}\cdot\vec{k} \right) - \omega t 
\coloneqq
k s - \omega t = ... 
\end{split}$${#eq-phase}

### Phaseshift:
$$\begin{split} &
\Delta\varphi = \Delta k \left( \vec{r}\cdot\vec{\Delta k} \right) - \Delta \omega t 
\coloneqq
\Delta k s - \Delta \omega t = ... 
\end{split}$${#eq-phaseshift}


### Matter

#### Refraction:
Refraction $\Leftrightarrow$ $\exists$ Matter; refraction causes dispersion
$$\begin{split} &
\eta = \frac{\tan\alpha}{\tan\beta} = \frac{\lambda_0}{\lambda} = 
c \sqrt{\varepsilon\mu}
\> \hat{=} \> 
\mathscr{E}_\beta^{-1} \mathscr{E}_\alpha = 
\frac{\varepsilon_\alpha}{\varepsilon_\beta} = ...
\end{split}$${#eq-refract}

#### Dispersion:
Dispersion $\Leftrightarrow$ $\exists$ Matter (dielctric madium or conductor); 
Dispersion $\neq$ Dissipation $\neq$ Diffusion
$$\begin{split} &
...
\end{split}$${#eq-dispers}


### Charge

#### Conductivity:
$$\begin{split} &
\sigma(\omega) = ...
\end{split}$${#eq-conductivity}

#### Dielectricity:
$$\begin{split} &
\varepsilon(\omega) = ...
\end{split}$${#eq-dielectricity}

#### Permeability:
$$\begin{split} &
\mu(\omega) = ...
\end{split}$${#eq-permeability}


### Conductor condition (charge conductive element for energy transfer):
$$\begin{split} & 
\sigma \cdot t \gg \varepsilon_0
\end{split}$${#eq-conductor}

### Slow current changing condition (quasi-stationary, low frequencies):
$$\begin{split} & 
\frac{v}{c} \ll \frac{1}{c}\frac{\mathscr{E}}{\mathscr{B}} \ll \frac{c}{v}
\end{split}$${#eq-slowcurrent}


## Energy of thin conductor (concentrated conductive medium without electric charge in its surrounding), Voltage (potentialdifference, tension):

$$\begin{split} &
V = 
U_1 - U_2 = 
r \mathscr{E} = 
\dot{\Psi} + R I + \frac{I}{C}t = 
L \dot{I} + R I + \frac{Q}{C}
\end{split}$${#eq-potential-3}

\

## Low Frequency
$$\begin{split} & \omega \ll \frac{1}{\mu \sigma} \frac{2}{r^2} \iff r \ll d \iff \rho \ll 1 \end{split}$${#eq-lowfreq-cond}
$$
L \approx const.    \qquad
C \approx const.    \qquad
D_S \approx 0
$$

## High Frequency
$$\begin{split} & \omega \gg \frac{1}{\mu \sigma} \frac{2}{r^2} \iff r \gg d \iff \rho \gg 1 \end{split}$${#eq-highfreq-cond}
$$
L(t) \neq const.    \qquad
C(t) \neq const.   \qquad
\textnormal{for Dipol: } D_S \propto \omega^4 \gg 0 
$$

\

## Continuity at Rest: Electic Charge
no Dissipation, no velocity, charge (ion) causes Electric Field


## Continuity at Movement: Magnetic Field
no Dissipation, Velocity constant, moved charge (ion) causes emergence of Magnetic Field


## Continuity at Acceleration: Radiation Energy
no Dissipation, Velocity changing, acceleration of charge (ion) causes emgergence of Radiation


## Continuity and periodic (harmoneous oscillation) Movement in VACUUM

$c = \frac{1}{\sqrt{\varepsilon_0\mu_0}} = \nu\lambda = \frac{\lambda}{T}$

$2\pi = k\lambda = T\omega = \frac{\omega}{\nu}$

$$
2\pi = k \lambda \gg kr_0 \ll 1
$$\linebreak$$
\omega = kc \ll \frac{c}{r_0}     \qquad
\nabla \cdot j = i \omega \varrho     \qquad
i \omega Q = 0
$$



## Continuity and periodic (harmoneous oscillation) Movement in MATTER

Refraction index $\eta$  emerges: $\varepsilon\mu = \left( \frac{\eta}{v_{ph}} \right)^2 \hat{=} \left( \frac{\eta}{c} \right)^2$

Dispersion: $k^2 = \varepsilon \mu \omega^2 + i \mu \sigma \omega$



## Near Field
static, vacuum, granular spacetime

$$
r \ll \lambda  = \frac{2\pi}{k}
\stackrel{\textnormal{vacuum}}{=}
\frac{2\pi}{ \frac{\omega}{c} }
\qquad
kr \ll 2\pi
$$

$$
\frac{w_m}{w_e} \sim \frac{ \frac{\vec{p}^2}{\varepsilon_0 r^6} }{ \frac{k^2 \mu_0 c^2 \vec{p}^2}{r^4} } \sim \left( kr \right)^2 \ll 1 
$$

$$
\vec{p} = \textnormal{elec. Dipol}
$$



## Far Field
static, vacuum, flat spacetime

accelerated movement -> Radiation in Far Field of charge source

$$
r \gg \lambda  = \frac{2\pi}{k}
\stackrel{\textnormal{vacuum}}{=}
\frac{2\pi}{ \frac{\omega}{c} }
\qquad
kr \gg 1
\qquad
r \gg kr_0^2 \ll 1
$$

$$
\frac{w_m}{w_e} =
\frac{ \frac{\varepsilon_0}{2} c^2 \left( \mathscr{B} \times \frac{r}{\left| r \right|} \right)^2 }{ \frac{\varepsilon_0}{2} c^2 \left( \mathscr{B} \times \frac{r}{\left| r \right|} \right)^2 } = 1
$$


## Dissipation in Vacuum
no Contiunuity of chrge/matter, no Refraction index, Reflection


## Dissipation in Matter
no Contiunuity of charge/matter with dielectricum, refraction merges, reflection, absorbtion


\

## Energy gain by excitation

{{< include C:/Users/erine/Desktop/Physics-Explorations/GitHub-Physics/Potentials/Content/Quant_h.qmd >}}

\

\Rightarrow 
Ionisation Energy of chemical element $E_i = n_i h\nu = n_i h\frac{\lambda}{c} = n_i \hbar\omega = n_i \frac{h}{k\lambda} \omega$

\Rightarrow 
Energy released (gained), see... @eq-potignit

- with mass (e.g. electron), Tunnel-Effect: $E_{gain} = E_{pot} - E_i = mc^2 - h\nu_i$

- massless (e.g. photon), Doppler-Effect (frequency shift): $E_{gain} = E_{kin} - E_i = h \left( \nu_0 - \nu_i \right) = \Delta\omega \hbar$



\


<!-- Electromagnectic Energy Exchange in Vacuum, Energy Balance -->
{{< include C:/Users/erine/Desktop/Physics-Explorations/GitHub-Physics/Potentials/Content/energy-balance.qmd >}}



# Electromagnectic Energy Exchange in Matter

- Near Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)
- Far Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)

... 



# Mechanical Energy Exchange in Vacuum

- Near Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)
- Far Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)

... 



# Mechanical Energy Exchange in Matter

- Near Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)
- Far Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)

... 



# Thermal Energy Exchange in Vaccumm

- Near Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)
- Far Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)

... 



# Thermal Energy Exchange in Matter

- Near Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)
- Far Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)

... 



# Gravitational Energy Exchange in Vacuum
.
- Near Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)
- Far Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)

... 



# Gravitational Energy Exchange in Matter

- Near Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)
- Far Field, linear vs. angular, time independent (static/rest, stationary/slow) vs. time dependent (dynamic, fast)

... 


# Localization and Fields of Energy Transport

Localization of energy density $w$ and of its energy transport $\mathscr{S}_{w}$ is where field force has strongest density. Fields for Forces, Energy, Momentum, Matter:

- Electromangnetic:
$$
\begin{rcases}
\text{Electric: } \mathscr{E}, \mathscr{D}, \mathscr{P}, \mathscr{\Phi_e} \\
\text{Magnetic: } \mathscr{B}, \mathscr{H}, \mathscr{M}, \mathscr{A}, \mathscr{\Phi_m}
\end{rcases}  \mathscr{S}, \mathscr{T} 
$$

- Thermal (skalar): $T$

- Gravitational: $G$





# Frequency Cause-Effect

{{< include C:/Users/erine/Desktop/Physics-Explorations/Content_repository/Frequency.qmd >}}


<!-- Boundry Conditions -->
{{< include C:/Users/erine/Desktop/Physics-Explorations/Content_repository/boundry-conditions.qmd >}}


<!-- Situations Conditions -->
{{< include C:/Users/erine/Desktop/Physics-Explorations/Content_repository/situations-conditions.qmd >}}


<!-- Operators -->
{{< include C:/Users/erine/Desktop/Physics-Explorations/Content_repository/Operators.qmd >}}

